on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
  
      - name: Install build
        run: python -m pip install build wheel
  
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
          unzip protoc-3.15.8-linux-x86_64.zip -d $HOME/.local

      - uses: actions/checkout@v2
      
      - run: python setup.py generate_py_protobufs
        shell: bash

      - run: python -m build .
        shell: bash
